### ISSUE TITLE
Completed Challenge

### ISSUE THREAD

**Issue by christopherturner** [christopherturner/scope-f17#1]
Hey @scopeusc!  Just wanted to let you know that I completed the first challenge, changing up some of the styling (coloring of the app) and added some default cards.

Feel free to see here: https://github.com/christopherturner/scope-f17/commit/9d818489799dccdaafe41ce99cbccc7b9a7a728f

**Comment by christopherturner** [comment]
@WilhelmWillie

**Comment by WilhelmWillie** [comment]
Can't close it for some reason but you're good! Nice job man
